---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - ""
  resources:
  - namespaces
  verbs:
  - create
  - get
  - list
  - watch
- apiGroups:
  - '*'
  resources:
  - '*'
  verbs:
  - '*'
- apiGroups:
  - platform.kubo.io
  resources:
  - stackdefinitions
  - stacks
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - platform.kubo.io
  resources:
  - stackdefinitions/finalizers
  - stacks/finalizers
  verbs:
  - update
- apiGroups:
  - platform.kubo.io
  resources:
  - stackdefinitions/status
  - stacks/status
  verbs:
  - get
  - patch
  - update
